name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use OCaml 4.11.1
      uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: 4.11.1
    - name: Use Node.js 14.16.1
      uses: actions/setup-node@v1
      with:
        node-version: 14.16.1
    - name: Install OCaml dependencies
      run: |
        git submodule init
        git submodule update --remote nuscr
        cd nuscr
        opam install -dt . --deps-only
        eval $(opam config env)
        dune build
        cd ..
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r codegen/requirements.txt
        pip install -r codegen/requirements.dev.txt
    - name: Run Python tests
      run: |
        eval $(opam config env)
        cd web-sandbox/node
        npm i
        cd ../browser
        npm i
        cd ../..
        python -m codegen.tests.system
